name: Deploy to Firebase Hosting and GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version compatible with Firebase

      - name: Install npm dependencies
        run: |
          npm install -g firebase-tools
          npm install

      - name: Configure Firebase credentials
        run: |
          echo "const firebaseConfig = {
            apiKey: '${{ AIzaSyDdRzTjyVu7cwvhoUFTqZsLlRnmHx77t_0 }}',
            authDomain: '${{ fir-website-32e50.firebaseapp.com }}',
            projectId: '${{ fir-website-32e50 }}',
            storageBucket: '${{ fir-website-32e50.appspot.com }}',
            messagingSenderId: '${{ 908676658823 }}',
            appId: '${{ 1:908676658823:web:35d7f2a8e453f2cbe8ea22 }}',
            measurementId: '${{ G-XQKPYCL968 }}'
          };" > public/firebase-config.js  # Adjust path as needed

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token ${{ AIzaSyDdRzTjyVu7cwvhoUFTqZsLlRnmHx77t_0 }}

  deploy_github_pages:
    runs-on: ubuntu-latest
    needs: build  # Ensure Firebase deploy finishes before deploying to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # You can change this to a specific version you prefer

      - name: Install dependencies
        run: |
          npm install firebase

      - name: Build project
        run: |
          npm run build  # Use this if you have a build step; otherwise, skip this

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ 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 }}  # Use the secret for the GitHub token
          publish_dir: ./  # Change this if your output directory is different
